# Generated by Django 2.0.5 on 2018-06-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Zomato_URL', models.CharField(max_length=250, unique=True)),
                ('Google_URL', models.CharField(help_text='Google Maps URL address is required.', max_length=250, unique=True)),
                ('TimeStamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('User', models.IntegerField(default=0)),
                ('Review', models.TextField()),
                ('TimeStamp', models.DateField(auto_now=True)),
                ('Rating', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectdata.BusiModel')),
            ],
        ),
    ]
