# Generated by Django 2.0.5 on 2018-07-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0002_auto_20180618_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='Polarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
