# Generated by Django 2.0.5 on 2018-07-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0003_scrapeddata_polarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='Polarity',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=12, null=True),
        ),
    ]
