# Generated by Django 2.0.5 on 2018-07-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0004_auto_20180702_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='Polarity',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True),
        ),
    ]
